services:
  banana-postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_DB: banana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - bananapgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev # for testing purposes
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realms/banana.json:/opt/keycloak/data/import/banana.json
    ports:
      - "8181:8080"
    networks:
      - banana

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis port on localhost
    volumes:
      - redis_data:/data 
      
volumes:
  bananapgdata:
  redis_data:
    driver: local
  
networks:
  banana:
    driver: bridge
