services:
  banana-postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_DB: banana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - bananapgdata:/var/lib/postgresql/data

volumes:
  bananapgdata:
