version: '2'
services:
  postgresql:
    image: postgres:16.2
    environment:
      POSTGRES_DB: banana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - bananapgdata:/var/lib/postgresql/data
volumes:
  bananapgdata:
