# Configuration locale pour le développement
# Ce fichier peut être modifié localement sans être commité

database:
  host: "localhost"
  port: "5434"
  schema: "banana"
  username: "postgres"
  password: "postgres"

oidc:
  realm_url: "http://localhost:8181/realms/Banana"
  base_url: "http://localhost:9000"

session:
  store_addr: "redis://127.0.0.1:6379"

cors:
  allowed_origin: "http://localhost:9000"
