apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.3
        command:
        - /opt/keycloak/bin/kc.sh
        - start-dev
        - --import-realm
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-realm-config
          mountPath: /opt/keycloak/data/import/banana.json
          subPath: banana.json
      volumes:
      - name: keycloak-realm-config
        configMap:
          name: keycloak-realm-config